name: Practo Test Pipeline
description: Orchestrates Java Selenium, Playwright Axe, and JMeter tests

on:
  workflow_dispatch:

jobs:
  run-all-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Orchestrator Repo
      uses: actions/checkout@v4

    - name: Checkout Java/Maven/Selenium Project
      uses: actions/checkout@v4
      with:
        repository: aymanebouchaara/PractoTestFramework
        path: java-selenium

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run Java Selenium Tests
      working-directory: java-selenium
      run: mvn clean -Dtest=CucumberTestRunner test
      continue-on-error: true

    - name: Upload ExtentReports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: extent-reports
        path: java-selenium/test-output/ExtentReport.html

    - name: Checkout Playwright/Axe Project
      uses: actions/checkout@v4
      with:
        repository: aymanebouchaara/PractoAccessibilityTesting
        path: playwright-axe

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install and Run Playwright Tests
      working-directory: playwright-axe
      run: |
        npm ci
        npx playwright install
        npm test

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-axe/a11y-reports/*.html

    - name: Checkout Performance Testing
      uses: actions/checkout@v4
      with:
        repository: aymanebouchaara/PractoPerformanceTesting
        path: PerformanceTesting

    - name: Run JMeter Tests
      uses: rbhadti94/apache-jmeter-action@v0.7.0
      with:
        testFilePath: PerformanceTesting/tests/
        outputReportsFolder: PerformanceTesting/execresults/html
        args: "-e"

    - name: Upload JMeter Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: PerformanceTesting/execresults/html



